application: uspolling2012
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

inbound_services:
- mail

libraries:
- name: lxml
  version: "latest"
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"

handlers:
- url: /static
  static_dir: static

- url: /
  script: handlers.home.app

- url: /api
  script: handlers.api.app